package hibernate.persistencia;
// Generated 08-21-2018 04:31:34 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Consultorios generated by hbm2java
 */
public class Consultorios implements java.io.Serializable {

    private Integer idConsultorio;
    private String nombre;
    private String ubicacion;
    private String telefono;
    private Set citases = new HashSet(0);

    public Consultorios() {
    }

    public Consultorios(String nombre, String ubicacion, String telefono) {
        this.nombre = nombre;
        this.ubicacion = ubicacion;
        this.telefono = telefono;

    }

    public Integer getIdConsultorio() {
        return this.idConsultorio;
    }

    public void setIdConsultorio(Integer idConsultorio) {
        this.idConsultorio = idConsultorio;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getUbicacion() {
        return this.ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Set getCitases() {
        return this.citases;
    }

    public void setCitases(Set citases) {
        this.citases = citases;
    }

    @Override
    public String toString() {
        return "Consultorios{" + "idConsultorio=" + idConsultorio + ", nombre=" + nombre + ", ubicacion=" + ubicacion + ", telefono=" + telefono +'}';
    }
    
}
