package hibernate.persistencia;
// Generated 08-21-2018 04:31:34 PM by Hibernate Tools 4.3.1



/**
 * Especialidades generated by hbm2java
 */
public class Especialidades  implements java.io.Serializable {


     private Integer idEspecialidad;
     private Medicos medicos;
     private String especialidad;

    public Especialidades() {
    }

    public Especialidades(Medicos medicos, String especialidad) {
       this.medicos = medicos;
       this.especialidad = especialidad;
    }
   
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


